-- Wait for game
repeat task.wait() until game:IsLoaded();

--UI Library
local Library = loadstring(game:HttpGet('https://raw.githubusercontent.com/Rain-Design/Libraries/main/Shaman/Library.lua'))()
local Window = Library:Window({
    Text = "Right 2 Fight"
})
local Flags = Library.Flags

local StuffTab = Window:Tab({
    Text = "Stuff"  
})
local KillAuraSection = StuffTab:Section({
    Text = "Kill Aura"
})
local DungeonsSection = StuffTab:Section({
    Text = "Dungeons"
})

local workspace = game:GetService("Workspace")
local Dungeons = game:GetService("Workspace").Map.Dungeons
-- Aura Related
getgenv().KillAura = false; 
local Move;
-- Dungeon Related
local Difficulty = ''
local DungeonTable = {}
local SelectedDungeon

-- Getting All Possible Arenas
for i,v in next, game:GetService("Workspace").Map.Dungeons:GetChildren() do
    table.insert(DungeonTable, v.Name)
end

-- Credits to JOSHNXTDOOR for the open source Kill Aura https://v3rmillion.net/showthread.php?tid=1150826
function FuncKillAura()
    for i,v in next, game:GetService("Workspace").Bots.AI:GetChildren() do
        local A_1 = {
            [1] = "damage",
            [2] = v.UpperTorso,
            [3] = Vector3.new(v.HumanoidRootPart.Position),
            [4] = game:GetService("ReplicatedFirst").Moves.BTStrike4,   
            [5] = Move,
            [6] = 0.67969219472527
        }
        game:GetService("ReplicatedStorage").Events.ME:FireServer(A_1)
        task.wait()
    end
end

KillAuraSection:Toggle({
    Text = "Enable Kill Aura",
    Flags = "KillAuraFlag",
    Callback = function(v)
    KillAura = v;
        if ( KillAura ) then
            task.spawn(function()
                while KillAura do
                    FuncKillAura()
                end
            end)
        end
    end
})

-- Difficulties
local DifficultyDropDown = DungeonsSection:Dropdown({
    Text = "Difficulty",
    List = {'Easy', 'Normal', 'Hard', 'Legend'},
    Callback = function(Value)
        Difficulty = Value;
    end
})

local ArenasDropDown = DungeonsSection:Dropdown({
    Text = "Dungeons",
    List = DungeonTable,
    Callback = function(Value)
        SelectedDungeon = Value;
    end
})

DungeonsSection:Button({
    Text = "Start Dungeon",
    Tooltip = "This will start the dungeon.",
    Callback = function()
        -- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

        local ohTable1 = {
            [1] = "dungeontime",
            [2] = Dungeons[SelectedDungeon].Area,
            [3] = Difficulty
        }

        game:GetService("ReplicatedStorage").Events.ME:FireServer(ohTable1)

        for i, val in pairs(ohTable1) do
            print(val)
        end
    end
})  
